// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHWLULoe19Cv-lTTHhxSkx-hkGFTMBoos',
    appId: '1:400013147984:web:79dcdf7784d6f753833655',
    messagingSenderId: '400013147984',
    projectId: 'charitey-97f31',
    authDomain: 'charitey-97f31.firebaseapp.com',
    storageBucket: 'charitey-97f31.firebasestorage.app',
    measurementId: 'G-D3QF7BT2RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdmAN6V1bYBaSuEOB5CTtb13mzL36IO64',
    appId: '1:400013147984:android:1bd105808bc78083833655',
    messagingSenderId: '400013147984',
    projectId: 'charitey-97f31',
    storageBucket: 'charitey-97f31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFaGS7x18_-7McaCacqYMBNrKHZPVc6mI',
    appId: '1:400013147984:ios:6a07fea4f7e08b36833655',
    messagingSenderId: '400013147984',
    projectId: 'charitey-97f31',
    storageBucket: 'charitey-97f31.firebasestorage.app',
    iosClientId: '400013147984-6i3su7uviau0k4ks8ram24krbnrg18cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.charityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFaGS7x18_-7McaCacqYMBNrKHZPVc6mI',
    appId: '1:400013147984:ios:6a07fea4f7e08b36833655',
    messagingSenderId: '400013147984',
    projectId: 'charitey-97f31',
    storageBucket: 'charitey-97f31.firebasestorage.app',
    iosClientId: '400013147984-6i3su7uviau0k4ks8ram24krbnrg18cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.charityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHWLULoe19Cv-lTTHhxSkx-hkGFTMBoos',
    appId: '1:400013147984:web:9db7735868d54790833655',
    messagingSenderId: '400013147984',
    projectId: 'charitey-97f31',
    authDomain: 'charitey-97f31.firebaseapp.com',
    storageBucket: 'charitey-97f31.firebasestorage.app',
    measurementId: 'G-3SB7RYW91V',
  );
}
