// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQIj6th0aijxmeHmzkRGRekZPXhP63C08',
    appId: '1:49324937832:web:2483eb7807d59da3a561dd',
    messagingSenderId: '49324937832',
    projectId: 'charitey-37ce8',
    authDomain: 'charitey-37ce8.firebaseapp.com',
    storageBucket: 'charitey-37ce8.firebasestorage.app',
    measurementId: 'G-GG71PRX0JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn9Tsy76rP_uJ1uUntzx1sjnuByzy0utk',
    appId: '1:49324937832:android:a09673ba5590f134a561dd',
    messagingSenderId: '49324937832',
    projectId: 'charitey-37ce8',
    storageBucket: 'charitey-37ce8.firebasestorage.app',
  );
}
